### ISSUE TITLE
Youtube channels working again

### ISSUE THREAD

**Issue by DareFail** [teamduck/remoteremote#2]
The predefined channels (i.e. FreddieW videos) that always have open rooms do not run because the youtube API is now on V3 

gdata.youtube.com/feeds/api/videos?q=good%20eats%20-LikeTheHat&start-index=1&max-results=50&v=2&alt=jsonc&format=5

is no longer a valid url for retrieving videos

**Comment by sammessina** [comment]
Looks like that API was shut down in 2015 and the new one is here: https://developers.google.com/youtube/v3/getting-started
Will update the code to use that instead.
